version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - worker

  redis:
    image: "redis:latest"
    restart: always

  worker:
    build: .
    command: ["celery", "-A", "tasks.celery", "worker", "--loglevel=info"]
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
